baseURL = 'https://farts.ie/'
languageCode = 'en-gb'
title = 'Abbans Gone and Done a Blog'
theme = 'farts-hugo-theme'

[Params]
    mainSections = ["post"]
    intro = true
    headline = "My headline"
    description = "Abbans Gone and Done a Blog"
    github = "https://github.com/Abban"
    twitter = "https://twitter.com/blunderjack"
    email = "yo@farts.ie"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[markup]
    [markup.highlight]
        style = 'gruvbox'
        noClasses = false
    [markup.goldmark]
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.parser]
            [markup.goldmark.parser.attribute]
                block = true
                title = true


